name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Set up Git configuration
        run: |
          git config --global user.email "simonlobgromov@gmail.com"
          git config --global user.name "Simonlob"
      
      - name: Sync with Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add huggingface https://Simonlob:$HF_TOKEN@huggingface.co/spaces/Simonlob/Akylai-Matcha-TTS
          git fetch --all
          git reset --hard huggingface/main
          git push huggingface main --force

